import type { ExportPlace } from '@holiday-planner/shared'

export interface DiscoverList {
  id: string
  title: string
  emoji: string
  description: string
  places: ExportPlace[]
}

export const DISCOVER_LISTS: DiscoverList[] = [
  {
    id: 'tokyo-restaurants',
    title: 'Top 50 Restaurants in Tokyo',
    emoji: '🍣',
    description: 'From legendary sushi counters to ramen icons and Michelin-starred kaiseki',
    places: [
      { name: 'Sukiyabashi Jiro Honten', type: 'RESTAURANT', lat: 35.6727, lng: 139.7640, address: 'Ginza, Tokyo', notes: 'The world\'s most famous sushi counter — Jiro Ono\'s legendary 10-seat basement', visited: false },
      { name: 'Narisawa', type: 'RESTAURANT', lat: 35.6651, lng: 139.7148, address: 'Minami-Aoyama, Tokyo', notes: '2 Michelin stars; innovative Japanese cuisine inspired by nature and satoyama', visited: false },
      { name: 'Den', type: 'RESTAURANT', lat: 35.6949, lng: 139.7566, address: 'Jinbocho, Tokyo', notes: '2 Michelin stars; playful and personal modern Japanese — one of Asia\'s 50 Best', visited: false },
      { name: "L'Effervescence", type: 'RESTAURANT', lat: 35.6592, lng: 139.7222, address: 'Nishi-Azabu, Tokyo', notes: '2 Michelin stars; French cuisine rooted in Japanese ingredients and philosophy', visited: false },
      { name: 'Nihonryori RyuGin', type: 'RESTAURANT', lat: 35.6600, lng: 139.7300, address: 'Roppongi, Tokyo', notes: '3 Michelin stars; Seiji Yamamoto\'s bold reimagining of Japanese cuisine', visited: false },
      { name: 'Sazenka', type: 'RESTAURANT', lat: 35.6471, lng: 139.7288, address: 'Minami-Azabu, Tokyo', notes: '3 Michelin stars; sophisticated Chinese cuisine in a tranquil Japanese setting', visited: false },
      { name: 'Florilège', type: 'RESTAURANT', lat: 35.6670, lng: 139.7159, address: 'Gaien-mae, Tokyo', notes: '2 Michelin stars; open-kitchen French with a focus on vegetables and local sourcing', visited: false },
      { name: 'Sushi Yoshitake', type: 'RESTAURANT', lat: 35.6714, lng: 139.7642, address: 'Ginza, Tokyo', notes: '3 Michelin stars; intimate 8-seat counter with exceptional Edomae technique', visited: false },
      { name: 'Koju', type: 'RESTAURANT', lat: 35.6716, lng: 139.7650, address: 'Ginza, Tokyo', notes: '2 Michelin stars; refined traditional kaiseki in a serene Ginza setting', visited: false },
      { name: 'Sushi Kanesaka', type: 'RESTAURANT', lat: 35.6717, lng: 139.7648, address: 'Ginza, Tokyo', notes: '3 Michelin stars; master Shinji Kanesaka\'s precise and seasonal omakase', visited: false },
      { name: 'Tempura Kondo', type: 'RESTAURANT', lat: 35.6712, lng: 139.7641, address: 'Ginza, Tokyo', notes: '2 Michelin stars; Fumio Kondo\'s legendary vegetable and seafood tempura', visited: false },
      { name: 'Sushi Sho', type: 'RESTAURANT', lat: 35.6861, lng: 139.7246, address: 'Yotsuya, Tokyo', notes: 'A near-mythical counter in a back alley; considered by many the world\'s best sushi', visited: false },
      { name: 'Sushi Saito', type: 'RESTAURANT', lat: 35.6680, lng: 139.7491, address: 'Toranomon, Tokyo', notes: 'Possibly the hardest reservation in Japan; Takashi Saito\'s pristine Edomae omakase', visited: false },
      { name: 'Ishikawa', type: 'RESTAURANT', lat: 35.7005, lng: 139.7440, address: 'Kagurazaka, Tokyo', notes: '3 Michelin stars; masterful kaiseki rooted in Kyoto tradition, deep in charming Kagurazaka', visited: false },
      { name: 'Esaki', type: 'RESTAURANT', lat: 35.6890, lng: 139.7019, address: 'Shinjuku area, Tokyo', notes: '3 Michelin stars; delicate and seasonal kaiseki in an intimate counter setting', visited: false },
      { name: 'Hamadaya', type: 'RESTAURANT', lat: 35.6847, lng: 139.7740, address: 'Nihonbashi, Tokyo', notes: 'Traditional kaiseki in a historic tatami restaurant near Nihonbashi', visited: false },
      { name: 'Mikawa Zezankyo', type: 'RESTAURANT', lat: 35.6780, lng: 139.7967, address: 'Fukagawa, Tokyo', notes: '2 Michelin stars; celebrated tempura in the old downtown shitamachi neighbourhood', visited: false },
      { name: 'Sushi Sawada', type: 'RESTAURANT', lat: 35.6718, lng: 139.7643, address: 'Ginza, Tokyo', notes: '3 Michelin stars; Koji Sawada\'s restrained and elegant Edomae omakase', visited: false },
      { name: 'Quintessence', type: 'RESTAURANT', lat: 35.6413, lng: 139.7285, address: 'Shirokanedai, Tokyo', notes: '3 Michelin stars; French chef Shuzo Kishida — one of the finest French restaurants in Asia', visited: false },
      { name: 'Hakkoku', type: 'RESTAURANT', lat: 35.6925, lng: 139.7659, address: 'Kanda, Tokyo', notes: '2 Michelin stars; innovative sushi where aged fish and unconventional courses dazzle', visited: false },
      { name: 'Ode', type: 'RESTAURANT', lat: 35.6697, lng: 139.7035, address: 'Harajuku, Tokyo', notes: '2 Michelin stars; thoughtful French with Japanese sensibility by Yuichiro Fujisaki', visited: false },
      { name: 'La Bonne Table', type: 'RESTAURANT', lat: 35.6499, lng: 139.7296, address: 'Minami-Azabu, Tokyo', notes: '2 Michelin stars; contemporary French by Naoki Matsuda in a quiet Azabu setting', visited: false },
      { name: 'Fuunji', type: 'RESTAURANT', lat: 35.6868, lng: 139.6987, address: 'Shinjuku, Tokyo', notes: 'Best tsukemen (dipping ramen) in Tokyo; rich hazel broth and thick flat noodles', visited: false },
      { name: 'Nakiryu', type: 'RESTAURANT', lat: 35.7314, lng: 139.7211, address: 'Minami-Otsuka, Tokyo', notes: '1 Michelin star; first ramen shop in the world to earn a Michelin star, famous tantanmen', visited: false },
      { name: 'Ichiran Shibuya', type: 'RESTAURANT', lat: 35.6595, lng: 139.7004, address: 'Shibuya, Tokyo', notes: 'Iconic solo-booth tonkotsu ramen chain; perfect for solo dining and flavour customisation', visited: false },
      { name: 'Taishoken Higashi-Ikebukuro', type: 'RESTAURANT', lat: 35.7291, lng: 139.7154, address: 'Higashi-Ikebukuro, Tokyo', notes: 'Birthplace of tsukemen; a Tokyo ramen pilgrimage site since 1961', visited: false },
      { name: 'Afuri Harajuku', type: 'RESTAURANT', lat: 35.6696, lng: 139.7025, address: 'Harajuku, Tokyo', notes: 'Elegant yuzu-shio ramen in a sleek modern setting; vegan options available', visited: false },
      { name: 'Ramen Nagi Golden Gai', type: 'RESTAURANT', lat: 35.6936, lng: 139.7006, address: 'Shinjuku Golden Gai, Tokyo', notes: 'Intense niboshi (sardine dashi) ramen hidden in the labyrinthine Golden Gai alley bars', visited: false },
      { name: 'Tsuta', type: 'RESTAURANT', lat: 35.7285, lng: 139.7391, address: 'Sugamo, Tokyo', notes: '1 Michelin star; elegant shoyu ramen made with truffle oil — the dish that put ramen on the fine-dining map', visited: false },
      { name: 'Tonki Meguro', type: 'RESTAURANT', lat: 35.6348, lng: 139.6990, address: 'Meguro, Tokyo', notes: 'The definitive Tokyo tonkatsu since 1939; long queue, counter seating, effortlessly crispy pork', visited: false },
      { name: 'Maisen Omotesando', type: 'RESTAURANT', lat: 35.6683, lng: 139.7118, address: 'Omotesando, Tokyo', notes: 'Famous tonkatsu chain in a converted public bathhouse; kurobuta pork cutlet perfection', visited: false },
      { name: 'Torishiki', type: 'RESTAURANT', lat: 35.6358, lng: 139.6992, address: 'Meguro, Tokyo', notes: '1 Michelin star; the most celebrated yakitori counter in Japan — every chicken part glorified', visited: false },
      { name: 'Bird Land', type: 'RESTAURANT', lat: 35.6710, lng: 139.7641, address: 'Ginza, Tokyo', notes: '1 Michelin star; refined Ginza yakitori in a sophisticated basement setting', visited: false },
      { name: 'Toritama', type: 'RESTAURANT', lat: 35.6544, lng: 139.7386, address: 'Azabu-Juban, Tokyo', notes: 'All-chicken yakitori omakase — even the sake is made from chicken, a truly unique experience', visited: false },
      { name: 'Nodaiwa', type: 'RESTAURANT', lat: 35.6570, lng: 139.7461, address: 'Higashi-Azabu, Tokyo', notes: 'Tokyo\'s finest unagi eel since 1850; charcoal-grilled wild eel in a traditional townhouse', visited: false },
      { name: 'Tofuya Ukai', type: 'RESTAURANT', lat: 35.6564, lng: 139.7474, address: 'Shiba, Tokyo', notes: 'Exquisite tofu kaiseki in a sprawling garden at the foot of Tokyo Tower', visited: false },
      { name: 'Sushisho Masa', type: 'RESTAURANT', lat: 35.7489, lng: 139.8007, address: 'Kita-Senju, Tokyo', notes: '40+ courses of extraordinary omakase sushi in a working-class neighbourhood — a pilgrimage', visited: false },
      { name: 'Imahan Ueno', type: 'RESTAURANT', lat: 35.7119, lng: 139.7770, address: 'Ueno, Tokyo', notes: 'Sukiyaki and shabu-shabu with premium wagyu since 1895 in an elegant traditional setting', visited: false },
      { name: 'Kandagawa Honten', type: 'RESTAURANT', lat: 35.6917, lng: 139.7673, address: 'Kanda, Tokyo', notes: 'Legendary unagi eel restaurant since 1837; historic riverside building, reserved counter seating', visited: false },
      { name: 'Yoshino Sushi Honten', type: 'RESTAURANT', lat: 35.6844, lng: 139.7742, address: 'Nihonbashi, Tokyo', notes: 'Traditional Edomae sushi since 1879; box sushi (oshizushi) prepared the old Tokyo way', visited: false },
      { name: 'Hamadaya Tempura Ginza Shimizu', type: 'RESTAURANT', lat: 35.6723, lng: 139.7634, address: 'Ginza, Tokyo', notes: 'Counter tempura with pristine seasonal ingredients; a quieter Ginza gem', visited: false },
      { name: 'Yakiniku Champion Shibuya', type: 'RESTAURANT', lat: 35.6589, lng: 139.7000, address: 'Shibuya, Tokyo', notes: 'Premium wagyu yakiniku with a lively atmosphere; a Tokyo yakiniku institution', visited: false },
      { name: 'Tableaux Daikanyama', type: 'RESTAURANT', lat: 35.6483, lng: 139.7022, address: 'Daikanyama, Tokyo', notes: 'Romantic French bistro in a leafy Daikanyama townhouse; reliable and charming', visited: false },
      { name: 'Hakata Ippudo Shibuya', type: 'RESTAURANT', lat: 35.6608, lng: 139.7011, address: 'Shibuya, Tokyo', notes: 'The global ramen chain that started in Fukuoka; rich hakata-style tonkotsu in Tokyo', visited: false },
      { name: 'Gyukatsu Motomura Shibuya', type: 'RESTAURANT', lat: 35.6596, lng: 139.7003, address: 'Shibuya, Tokyo', notes: 'Cook-it-yourself beef katsu on a hot stone; rare and juicy wagyu beef cutlet sensation', visited: false },
      { name: 'Soba Kokoro', type: 'RESTAURANT', lat: 35.6685, lng: 139.7088, address: 'Jingumae, Tokyo', notes: 'Artisan handmade soba in a calm setting near Harajuku; outstanding tsuyu dipping broth', visited: false },
      { name: 'Ramen Hayashida', type: 'RESTAURANT', lat: 35.6920, lng: 139.6988, address: 'Shinjuku, Tokyo', notes: 'Award-winning clear shoyu ramen with impeccable broth and house-made noodles', visited: false },
      { name: 'Sushi Isshin', type: 'RESTAURANT', lat: 35.6742, lng: 139.7375, address: 'Akasaka, Tokyo', notes: 'Excellent-value omakase sushi in Akasaka; skilled itamae and serious seasonal fish', visited: false },
      { name: 'Katsukura Shinjuku', type: 'RESTAURANT', lat: 35.6919, lng: 139.6935, address: 'Shinjuku, Tokyo', notes: 'Upscale tonkatsu set meals with free-flow rice and cabbage; grind your own sesame', visited: false },
      { name: 'Izakaya Torichan', type: 'RESTAURANT', lat: 35.6750, lng: 139.7540, address: 'Akasaka, Tokyo', notes: 'Lively traditional izakaya with excellent grilled chicken skewers and seasonal small plates', visited: false },
    ],
  },

  {
    id: 'osaka-restaurants',
    title: 'Top 50 Restaurants in Osaka',
    emoji: '🦑',
    description: 'Kuidaore capital of Japan — from Michelin stars to street food legends',
    places: [
      { name: 'Hajime', type: 'RESTAURANT', lat: 34.6810, lng: 135.4896, address: 'Nishi-ku, Osaka', notes: '3 Michelin stars; Hajime Yoneda\'s French cuisine with Japanese precision — ecological and visionary', visited: false },
      { name: 'Kashiwaya', type: 'RESTAURANT', lat: 34.7597, lng: 135.5151, address: 'Suita, Osaka', notes: '3 Michelin stars; classic kaiseki in a serene garden setting north of the city', visited: false },
      { name: 'La Cime', type: 'RESTAURANT', lat: 34.6711, lng: 135.5016, address: 'Minami-Semba, Osaka', notes: '2 Michelin stars; Yusuke Takada\'s refined French-Japanese cuisine in an intimate dining room', visited: false },
      { name: 'Taian', type: 'RESTAURANT', lat: 35.6697, lng: 135.5018, address: 'Minami-Semba, Osaka', notes: '2 Michelin stars; Takayuki Inoue\'s seasonal kaiseki with exceptional produce sourcing', visited: false },
      { name: 'Koryu', type: 'RESTAURANT', lat: 34.6747, lng: 135.5004, address: 'Shinsaibashi, Osaka', notes: '2 Michelin stars; elegant kappo cuisine where the chef\'s skill is on full display at the counter', visited: false },
      { name: 'Fujiya 1935', type: 'RESTAURANT', lat: 34.6817, lng: 135.5184, address: 'Tanimachi, Osaka', notes: '2 Michelin stars; Tetsuya Fujiwara blends French technique with Japanese tradition in a tranquil townhouse', visited: false },
      { name: 'Crony', type: 'RESTAURANT', lat: 34.6693, lng: 135.5007, address: 'Minami-Semba, Osaka', notes: '1 Michelin star; modern European with a relaxed bistro vibe, popular with Osaka\'s food-savvy crowd', visited: false },
      { name: 'Aizuya Honten', type: 'RESTAURANT', lat: 34.6547, lng: 135.5065, address: 'Shinsekai, Osaka', notes: 'Kushikatsu pioneer since 1929 in the retro Shinsekai district; the original double-dipping ban', visited: false },
      { name: 'Ganso Kushikatsu Daruma Shinsekai', type: 'RESTAURANT', lat: 34.6548, lng: 135.5063, address: 'Shinsekai, Osaka', notes: 'The iconic brand that spread kushikatsu across Japan; queue outside the tiger-painted Shinsekai shop', visited: false },
      { name: 'Daruma Honten Dotonbori', type: 'RESTAURANT', lat: 34.6695, lng: 135.5024, address: 'Dotonbori, Osaka', notes: 'Famous kushikatsu chain in bustling Dotonbori; crispy deep-fried skewers in a lively setting', visited: false },
      { name: 'Mizuno', type: 'RESTAURANT', lat: 34.6692, lng: 135.5015, address: 'Dotonbori, Osaka', notes: 'Osaka\'s most famous okonomiyaki — long queue, worth the wait; traditional Osaka-style savory pancake', visited: false },
      { name: 'Chibo Dotonbori', type: 'RESTAURANT', lat: 34.6693, lng: 135.5012, address: 'Dotonbori, Osaka', notes: 'Popular okonomiyaki restaurant with great river views; teppan-grilled tableside', visited: false },
      { name: 'Fukutaro', type: 'RESTAURANT', lat: 34.6651, lng: 135.5062, address: 'Namba, Osaka', notes: 'Beloved local okonomiyaki and modan-yaki spot in Namba; packed with regulars, casual and delicious', visited: false },
      { name: 'Ajinoya Dotonbori', type: 'RESTAURANT', lat: 34.6692, lng: 135.5016, address: 'Dotonbori, Osaka', notes: 'Lively Dotonbori okonomiyaki with show-cooking on a teppan grill; popular with tourists and locals', visited: false },
      { name: 'Takoyaki Yamamoto Dotonbori', type: 'RESTAURANT', lat: 34.6694, lng: 135.5024, address: 'Dotonbori, Osaka', notes: 'Classic Osaka takoyaki; crispy outside, gooey inside, topped with bonito flakes and sauce', visited: false },
      { name: 'Kukuru Dotonbori', type: 'RESTAURANT', lat: 34.6693, lng: 135.5018, address: 'Dotonbori, Osaka', notes: 'Excellent takoyaki made fresh in rows outside the shop; a Dotonbori staple', visited: false },
      { name: 'Wanaka Dotonbori', type: 'RESTAURANT', lat: 34.6691, lng: 135.5019, address: 'Dotonbori, Osaka', notes: 'One of the most popular takoyaki counters in Osaka; neat technique and perfectly balanced flavour', visited: false },
      { name: 'Zuboraya Dotonbori', type: 'RESTAURANT', lat: 34.6693, lng: 135.5021, address: 'Dotonbori, Osaka', notes: 'Famous fugu blowfish restaurant under a giant inflatable puffer fish sign on the Dotonbori strip', visited: false },
      { name: 'Kani Doraku Dotonbori', type: 'RESTAURANT', lat: 34.6694, lng: 135.5022, address: 'Dotonbori, Osaka', notes: 'The landmark crab restaurant with a moving mechanical crab above the entrance; Dotonbori icon since 1960', visited: false },
      { name: 'Endo Sushi', type: 'RESTAURANT', lat: 34.6907, lng: 135.4835, address: 'Osaka Central Wholesale Fish Market', notes: 'The earliest opening sushi counter in Osaka, catering to fish market workers since dawn', visited: false },
      { name: 'Harukoma Sushi', type: 'RESTAURANT', lat: 34.6638, lng: 135.5059, address: 'Kuromon Market, Osaka', notes: 'Fresh sushi counter inside Kuromon Ichiba market; market-fresh fish at excellent prices', visited: false },
      { name: 'Takoume', type: 'RESTAURANT', lat: 34.6636, lng: 135.5060, address: 'Kuromon Market, Osaka', notes: 'Beloved oden stall in Kuromon market; warm hearty broth-simmered ingredients since 1844', visited: false },
      { name: 'Dotonbori Imai', type: 'RESTAURANT', lat: 34.6691, lng: 135.5018, address: 'Dotonbori, Osaka', notes: 'Classic Osaka udon in a traditional shop; dashi-forward broth made from kombu and katsuobushi', visited: false },
      { name: 'Kinryu Ramen Dotonbori', type: 'RESTAURANT', lat: 34.6693, lng: 135.5020, address: 'Dotonbori, Osaka', notes: '24-hour ramen stand beneath a giant red dragon; Osaka\'s most famous late-night ramen spot', visited: false },
      { name: 'Matsuzakagyu Yamamoto', type: 'RESTAURANT', lat: 34.6698, lng: 135.5021, address: 'Dotonbori, Osaka', notes: 'Premium Matsuzaka wagyu beef in multiple preparations; a carnivore\'s dream on the Dotonbori strip', visited: false },
      { name: 'Yakiniku M Kitashinchi', type: 'RESTAURANT', lat: 34.6995, lng: 135.4960, address: 'Kitashinchi, Osaka', notes: 'Upscale wagyu yakiniku in the Kitashinchi entertainment district; extraordinary marbled beef', visited: false },
      { name: 'Kappo Ishibashi', type: 'RESTAURANT', lat: 34.6941, lng: 135.4811, address: 'Fukushima, Osaka', notes: 'Traditional kappo counter in trendy Fukushima; seasonal ingredients cooked with care and precision', visited: false },
      { name: 'Honke Shibatoya', type: 'RESTAURANT', lat: 34.6649, lng: 135.5000, address: 'Namba, Osaka', notes: 'Historic unagi eel restaurant in Namba; charcoal-grilled eel on rice in a classic atmosphere', visited: false },
      { name: 'Tsurutontan Shinsaibashi', type: 'RESTAURANT', lat: 34.6740, lng: 135.5003, address: 'Shinsaibashi, Osaka', notes: 'Oversized bowls of premium udon with creative toppings; reliably excellent and open very late', visited: false },
      { name: 'Nishiya Tenma', type: 'RESTAURANT', lat: 34.6968, lng: 135.5169, address: 'Tenma, Osaka', notes: 'Atmospheric yakitori in the Tenma food district; smoke-filled alley, excellent grilled chicken', visited: false },
      { name: 'Yakitori Toritomo Tenma', type: 'RESTAURANT', lat: 34.6970, lng: 135.5166, address: 'Tenma, Osaka', notes: 'Local favourite yakitori in vibrant Tenma; cheap, smoky, and absolutely delicious', visited: false },
      { name: 'Kadoya Tennoji', type: 'RESTAURANT', lat: 34.6508, lng: 135.5160, address: 'Tennoji, Osaka', notes: 'Legendary Osaka beef cutlet (gyukatsu) — thin slices of wagyu in a crispy crust since 1967', visited: false },
      { name: 'Akashiya Higobashi', type: 'RESTAURANT', lat: 34.6872, lng: 135.4885, address: 'Higobashi, Osaka', notes: 'Refined Osaka sushi with a local following; excellent quality without the Dotonbori tourist premium', visited: false },
      { name: 'Nakamura Minami-Semba', type: 'RESTAURANT', lat: 34.6703, lng: 135.5009, address: 'Minami-Semba, Osaka', notes: 'Creative French-Japanese fusion by a young chef; relaxed atmosphere and great value kaiseki lunch', visited: false },
      { name: 'Ichibancho Grill', type: 'RESTAURANT', lat: 34.6991, lng: 135.4962, address: 'Kitashinchi, Osaka', notes: 'Theatrical teppanyaki in Kitashinchi; wagyu, lobster and vegetables prepared on a blazing iron plate', visited: false },
      { name: 'Aux Amis Umeda', type: 'RESTAURANT', lat: 34.7025, lng: 135.4980, address: 'Umeda, Osaka', notes: 'Classic French brasserie in Umeda; reliable steak frites, French wine, and an easy Parisian vibe', visited: false },
      { name: 'Sushi Oomori Shinsaibashi', type: 'RESTAURANT', lat: 34.6747, lng: 135.5003, address: 'Shinsaibashi, Osaka', notes: 'Neighbourhood sushi counter with excellent omakase; fair pricing and skilled itamae', visited: false },
      { name: 'Shintaro Shinsaibashi', type: 'RESTAURANT', lat: 34.6744, lng: 135.5000, address: 'Shinsaibashi, Osaka', notes: 'Classic sukiyaki and shabu-shabu with premium Kobe and Matsuzaka beef; refined and traditional', visited: false },
      { name: 'Kurumaya Namba', type: 'RESTAURANT', lat: 34.6650, lng: 135.5001, address: 'Namba, Osaka', notes: 'Old-school hand-cut soba in a no-frills setting; one of Osaka\'s most authentic soba spots', visited: false },
      { name: 'Ramen Yamaoka Umeda', type: 'RESTAURANT', lat: 34.7024, lng: 135.4988, address: 'Umeda, Osaka', notes: 'Rich and creamy tonkotsu ramen near Umeda station; popular late-night spot with the after-work crowd', visited: false },
      { name: 'Osaka Ohsho Namba', type: 'RESTAURANT', lat: 34.6656, lng: 135.5007, address: 'Namba, Osaka', notes: 'Osaka\'s most beloved gyoza chain — crispy pan-fried dumplings with a secret recipe since 1969', visited: false },
      { name: 'Steak Gusto Dotonbori', type: 'RESTAURANT', lat: 34.6695, lng: 135.5015, address: 'Dotonbori, Osaka', notes: 'Affordable steak sets in the heart of Dotonbori; great value for a proper sit-down meal', visited: false },
      { name: 'Suju Ryori Yoshida', type: 'RESTAURANT', lat: 34.6648, lng: 135.5005, address: 'Namba, Osaka', notes: 'Traditional Japanese cuisine in a serene setting; seasonal multi-course meals with Osaka flavour', visited: false },
      { name: 'Tampopo Namba', type: 'RESTAURANT', lat: 34.6660, lng: 135.5010, address: 'Namba, Osaka', notes: 'Friendly izakaya with excellent grilled fish, tofu dishes and cold Osaka craft beer', visited: false },
      { name: 'Tenobe Somen Yamamoto', type: 'RESTAURANT', lat: 34.7022, lng: 135.4985, address: 'Umeda, Osaka', notes: 'Hand-stretched somen noodles in hot and cold preparations; a refined noodle experience', visited: false },
      { name: 'Hatago Kitashinchi', type: 'RESTAURANT', lat: 34.7000, lng: 135.4958, address: 'Kitashinchi, Osaka', notes: 'Italian-Japanese fusion in the Kitashinchi nightlife district; excellent pasta and Japanese sharing plates', visited: false },
      { name: 'Jukuren Shokunin no Mise Yanagisawa', type: 'RESTAURANT', lat: 34.6756, lng: 135.4997, address: 'Shinsaibashi, Osaka', notes: 'Artisan ramen from a master craftsman; small queue, handmade noodles, deeply satisfying broth', visited: false },
      { name: 'Hana Grill Kitashinchi', type: 'RESTAURANT', lat: 34.6992, lng: 135.4963, address: 'Kitashinchi, Osaka', notes: 'Elegant teppanyaki with premium ingredients; a great choice for a special night in Osaka', visited: false },
      { name: 'Mametatsu Semba', type: 'RESTAURANT', lat: 34.6730, lng: 135.5002, address: 'Semba, Osaka', notes: 'Refined Japanese cuisine with focus on tofu and seasonal ingredients; quiet and meditative', visited: false },
      { name: 'Fugetsu Dotonbori', type: 'RESTAURANT', lat: 34.6692, lng: 135.5013, address: 'Dotonbori, Osaka', notes: 'Osaka okonomiyaki chain with decades of history; busy, tasty, and quintessentially Osaka', visited: false },
    ],
  },

  {
    id: 'amsterdam-todo',
    title: '30 Things to Do in Amsterdam',
    emoji: '🚲',
    description: 'World-class museums, canal boat rides, markets and hidden courtyards',
    places: [
      { name: 'Rijksmuseum', type: 'MUSEUM', lat: 52.3600, lng: 4.8852, address: 'Museumstraat 1, Amsterdam', notes: 'The Netherlands\' greatest museum; Rembrandt\'s Night Watch and Vermeer\'s The Milkmaid are unmissable', visited: false },
      { name: 'Van Gogh Museum', type: 'MUSEUM', lat: 52.3584, lng: 4.8810, address: 'Museumplein 6, Amsterdam', notes: 'Largest Van Gogh collection in the world; 200 paintings in chronological order of his troubled genius', visited: false },
      { name: 'Anne Frank House', type: 'MUSEUM', lat: 52.3752, lng: 4.8839, address: 'Westermarkt 20, Amsterdam', notes: 'The hidden annex where Anne Frank hid for two years; a deeply moving and essential visit', visited: false },
      { name: 'Stedelijk Museum', type: 'MUSEUM', lat: 52.3579, lng: 4.8799, address: 'Museumplein 10, Amsterdam', notes: 'Modern and contemporary art from Mondrian to Jeff Koons; striking building with a distinctive white bathtub extension', visited: false },
      { name: 'Heineken Experience', type: 'MUSEUM', lat: 52.3576, lng: 4.8921, address: 'Stadhouderskade 78, Amsterdam', notes: 'Interactive brewery tour in the original 1867 Heineken brewery; ends with fresh pours and plenty of fun', visited: false },
      { name: 'NEMO Science Museum', type: 'MUSEUM', lat: 52.3743, lng: 4.9121, address: 'Oosterdok 2, Amsterdam', notes: 'Hands-on science museum shaped like a ship; brilliant for all ages, and the rooftop terrace has great views', visited: false },
      { name: 'Artis Royal Zoo', type: 'OTHER', lat: 52.3657, lng: 4.9162, address: 'Plantage Kerklaan 38-40, Amsterdam', notes: 'One of Europe\'s oldest zoos (1838); beautiful historic grounds with planetarium and aquarium included', visited: false },
      { name: 'Vondelpark', type: 'NATURE', lat: 52.3579, lng: 4.8686, address: 'Vondelpark, Amsterdam', notes: 'Amsterdam\'s beloved central park; ideal for cycling, picnics and watching street performers on sunny days', visited: false },
      { name: 'Albert Cuyp Market', type: 'MARKET', lat: 52.3543, lng: 4.8925, address: 'Albert Cuypstraat, Amsterdam', notes: 'Europe\'s largest outdoor daily market in the De Pijp neighbourhood; fresh stroopwafels, herring and fabrics', visited: false },
      { name: 'Bloemenmarkt', type: 'MARKET', lat: 52.3672, lng: 4.8909, address: 'Singel, Amsterdam', notes: 'The world\'s only floating flower market on the Singel canal; tulip bulbs, seeds and fresh cut flowers', visited: false },
      { name: 'Canal Boat Tour', type: 'OTHER', lat: 52.3777, lng: 4.9003, address: 'Centraal Station, Amsterdam', notes: 'Cruise Amsterdam\'s UNESCO-listed canal ring; hour-long tours depart regularly from Centraal Station', visited: false },
      { name: 'EYE Film Institute', type: 'MUSEUM', lat: 52.3844, lng: 4.9004, address: 'IJpromenade 1, Amsterdam', notes: 'Striking white film museum across the IJ from Centraal; free ferry, great architecture, film history exhibitions', visited: false },
      { name: 'Rembrandt House Museum', type: 'MUSEUM', lat: 52.3692, lng: 4.9007, address: 'Jodenbreestraat 4, Amsterdam', notes: 'The restored 17th-century house where Rembrandt lived and worked; fascinating reconstruction of his studio and etchings', visited: false },
      { name: 'Jewish Historical Museum', type: 'MUSEUM', lat: 52.3670, lng: 4.9019, address: 'Nieuwe Amstelstraat 1, Amsterdam', notes: 'Four interconnected historic synagogues telling the rich history of Jewish life in the Netherlands', visited: false },
      { name: 'Moco Museum', type: 'MUSEUM', lat: 52.3584, lng: 4.8817, address: 'Honthorststraat 20, Amsterdam', notes: 'Modern and contemporary art museum in a grand villa; permanent Banksy collection and rotating major exhibitions', visited: false },
      { name: 'Foam Photography Museum', type: 'MUSEUM', lat: 52.3626, lng: 4.8980, address: 'Keizersgracht 609, Amsterdam', notes: 'Excellent photography museum in a canal house; world-class rotating exhibitions across four floors', visited: false },
      { name: 'Micropia', type: 'MUSEUM', lat: 52.3661, lng: 4.9165, address: 'Plantage Kerklaan 38, Amsterdam', notes: 'Unique microbe zoo next to Artis; the only museum in the world dedicated entirely to microorganisms', visited: false },
      { name: 'Begijnhof', type: 'OTHER', lat: 52.3698, lng: 4.8900, address: 'Begijnhof, Amsterdam', notes: 'A hidden medieval courtyard of historic almshouses just off Spui; one of Amsterdam\'s most peaceful secrets', visited: false },
      { name: 'Westerkerk', type: 'OTHER', lat: 52.3746, lng: 4.8844, address: 'Prinsengracht 281, Amsterdam', notes: 'The tallest church in Amsterdam with a climbable tower offering panoramic views; Anne Frank heard its bells', visited: false },
      { name: 'Jordaan Neighbourhood Walk', type: 'NATURE', lat: 52.3741, lng: 4.8817, address: 'Jordaan, Amsterdam', notes: 'Amsterdam\'s most atmospheric quarter; narrow streets, independent galleries, cafés and picturesque hofjes (courtyards)', visited: false },
      { name: 'De Pijp Neighbourhood', type: 'OTHER', lat: 52.3535, lng: 4.8953, address: 'De Pijp, Amsterdam', notes: 'Vibrant multicultural neighbourhood with great cafés, the Albert Cuyp Market and the city\'s best coffee shops', visited: false },
      { name: 'Leidseplein', type: 'OTHER', lat: 52.3626, lng: 4.8832, address: 'Leidseplein, Amsterdam', notes: 'Amsterdam\'s entertainment hub; street performers, trams, theatre and the famous Paradiso music venue nearby', visited: false },
      { name: 'Rembrandtplein', type: 'OTHER', lat: 52.3669, lng: 4.8984, address: 'Rembrandtplein, Amsterdam', notes: 'Lively square with an iconic Rembrandt statue surrounded by 3D Night Watch figures; buzzing nightlife', visited: false },
      { name: 'Foodhallen', type: 'MARKET', lat: 52.3623, lng: 4.8723, address: 'Bellamyplein 51, Amsterdam', notes: 'Indoor street food market in a converted tram depot in the Oud-West; 20+ stalls, craft beer and cocktails', visited: false },
      { name: "Brouwerij 't IJ", type: 'BAR', lat: 52.3668, lng: 4.9283, address: 'Funenkade 7, Amsterdam', notes: 'Craft brewery inside a working windmill; tour the mill, taste the IPA on the terrace — a uniquely Amsterdam experience', visited: false },
      { name: "A'DAM Lookout", type: 'OTHER', lat: 52.3843, lng: 4.9008, address: 'Overhoeksplein 5, Amsterdam', notes: 'Observation deck with 360° views over Amsterdam; outdoor swing extends over the edge for the brave', visited: false },
      { name: 'Paradiso Amsterdam', type: 'OTHER', lat: 52.3620, lng: 4.8821, address: 'Weteringschans 6-8, Amsterdam', notes: 'Legendary music venue in a converted 19th-century church; everyone from The Rolling Stones to Nirvana has played here', visited: false },
      { name: 'Hortus Botanicus', type: 'NATURE', lat: 52.3661, lng: 4.9087, address: 'Plantage Middenlaan 2a, Amsterdam', notes: 'One of the world\'s oldest botanical gardens (1638); beautiful greenhouses with rare palms, cycads and cacti', visited: false },
      { name: 'Waterlooplein Flea Market', type: 'MARKET', lat: 52.3681, lng: 4.9006, address: 'Waterlooplein, Amsterdam', notes: 'Amsterdam\'s largest flea market running since 1886; vintage clothing, antiques, bikes and second-hand curiosities', visited: false },
      { name: 'NDSM Wharf', type: 'OTHER', lat: 52.4011, lng: 4.8869, address: 'NDSM-plein, Amsterdam Noord', notes: 'Former shipyard turned creative hub; street art, pop-up festivals, film sets and a thriving artist community across the IJ', visited: false },
    ],
  },

  {
    id: 'utrecht-see',
    title: '20 Things to See in Utrecht',
    emoji: '🗼',
    description: 'Medieval towers, hidden gardens, world-class museums and canal wharfs',
    places: [
      { name: 'Dom Tower', type: 'OTHER', lat: 52.0906, lng: 5.1213, address: 'Domplein 9, Utrecht', notes: 'The tallest church tower in the Netherlands at 112m; climb 465 steps for sweeping views over Utrecht and the countryside', visited: false },
      { name: 'Dom Church (Domkerk)', type: 'OTHER', lat: 52.0904, lng: 5.1216, address: 'Achter de Dom 1, Utrecht', notes: 'Gothic cathedral whose nave famously collapsed in a 1674 storm, leaving the detached tower; beautiful cloisters remain', visited: false },
      { name: 'Centraal Museum Utrecht', type: 'MUSEUM', lat: 52.0851, lng: 5.1182, address: 'Agnietenstraat 1, Utrecht', notes: 'Utrecht\'s main art and history museum; includes a Rietveld chair collection and a Viking ship excavated in the city', visited: false },
      { name: 'Museum Catharijneconvent', type: 'MUSEUM', lat: 52.0920, lng: 5.1175, address: 'Lange Nieuwstraat 38, Utrecht', notes: 'The Netherlands\' most important museum for religious art and culture; breathtaking medieval manuscripts and altarpieces', visited: false },
      { name: 'Nederlands Spoorwegmuseum (Railway Museum)', type: 'MUSEUM', lat: 52.0943, lng: 5.1245, address: 'Maliebaanstation, Utrecht', notes: 'Spectacular railway museum in a Victorian station; dozens of historic locomotives and immersive themed halls', visited: false },
      { name: 'Rietveld Schröder House', type: 'MUSEUM', lat: 52.0819, lng: 5.1507, address: 'Prins Hendriklaan 50, Utrecht', notes: 'UNESCO World Heritage Site; Gerrit Rietveld\'s radical 1924 modernist masterpiece with movable walls and De Stijl colours', visited: false },
      { name: 'Museum Speelklok', type: 'MUSEUM', lat: 52.0930, lng: 5.1215, address: 'Steenweg 6, Utrecht', notes: 'Magical museum of self-playing musical instruments; hourly guided tours bring giant fairground organs and clockwork music boxes to life', visited: false },
      { name: 'Botanic Gardens Utrecht (Hortus)', type: 'NATURE', lat: 52.0881, lng: 5.1276, address: 'Budapestlaan 17, Utrecht', notes: 'Peaceful university botanical garden with tropical greenhouses, rock gardens and a spectacular butterfly house', visited: false },
      { name: 'Oudegracht Canal & Wharfs', type: 'NATURE', lat: 52.0905, lng: 5.1178, address: 'Oudegracht, Utrecht', notes: 'Utrecht\'s unique double-level canal; walk the medieval wharf cellars now turned into cafés and restaurants', visited: false },
      { name: 'Trajectum Lumen Night Route', type: 'OTHER', lat: 52.0908, lng: 5.1200, address: 'Oudegracht, Utrecht', notes: 'Free after-dark light art route along the canals; 25 illuminated artworks transform Utrecht\'s historic centre after sunset', visited: false },
      { name: 'Kasteel de Haar', type: 'OTHER', lat: 52.1209, lng: 4.9996, address: 'Kasteellaan 1, Haarzuilens', notes: 'Netherlands\' largest castle; neo-Gothic fairytale architecture surrounded by formal gardens, just west of Utrecht', visited: false },
      { name: 'TivoliVredenburg', type: 'OTHER', lat: 52.0935, lng: 5.1137, address: 'Vredenburgkade 11, Utrecht', notes: 'Landmark music complex with five halls for everything from classical to electronic; visit for a concert or just admire the architecture', visited: false },
      { name: 'Wilhelminapark', type: 'NATURE', lat: 52.0832, lng: 5.1329, address: 'Wilhelminapark, Utrecht', notes: 'Elegant Victorian park with a café pavilion, rose garden and weekly local market; Utrecht\'s prettiest park', visited: false },
      { name: 'Griftpark', type: 'NATURE', lat: 52.0984, lng: 5.1203, address: 'Griftpark, Utrecht', notes: 'Relaxed community park along the Grift river; popular for picnics, urban beach events and the open-air theatre in summer', visited: false },
      { name: 'Ledig Erf Square', type: 'BAR', lat: 52.0909, lng: 5.1267, address: 'Ledig Erf, Utrecht', notes: 'Sunny canal-side terrace square lined with café chairs; the best spot in Utrecht for an afternoon beer or coffee', visited: false },
      { name: 'Pandhof (Secret Garden)', type: 'NATURE', lat: 52.0901, lng: 5.1228, address: 'Pandhof, Utrecht', notes: 'A tranquil medieval cloister garden hidden behind the Dom Church; one of the most peaceful spots in the Netherlands', visited: false },
      { name: 'Winkel van Sinkel', type: 'OTHER', lat: 52.0914, lng: 5.1173, address: 'Oudegracht 158, Utrecht', notes: 'Grand café in a stunning 1820s neoclassical building on the Oudegracht; beautifully restored with weekend club nights below', visited: false },
      { name: 'Fort Vechten', type: 'OTHER', lat: 52.0761, lng: 5.2000, address: 'Arnhemsebovenweg 70, Bunnik', notes: 'Intact 19th-century water defence fort east of Utrecht; moat, earthworks and a fascinating military history museum', visited: false },
      { name: 'Brouwerij De Leckere', type: 'BAR', lat: 52.0993, lng: 5.0948, address: 'De Leckere, Utrecht', notes: 'Utrecht\'s pioneering craft brewery in a windmill; brewery tours and tasting sessions on weekends', visited: false },
      { name: 'Miffy Museum (Nijntje Plein)', type: 'MUSEUM', lat: 52.0932, lng: 5.1143, address: 'Agnietenstraat 2, Utrecht', notes: 'Charming museum dedicated to Miffy (Nijntje), born in Utrecht; creator Dick Bruna\'s studio and interactive exhibits for children', visited: false },
    ],
  },
]
